{{- if and .Values.enabled (include "openhands.keycloakProvisionRealm" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-template
data:
  allhands-realm-github-provider.json.tmpl: |-
{{ .Files.Get "files/allhands-realm-github-provider.json.tmpl" | indent 4 }}
{{- end }}
