{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: openhands-mcp-service
  labels:
    {{- include "openhands.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
    app: openhands-mcp
spec:
  ports:
  - name: openhands-mcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: openhands-mcp
  type: ClusterIP
{{- end }}