#!/bin/bash
# =============================================================================
# Create Branch Deployment Values File
# =============================================================================
# Creates a Helm values file for deploying an OpenHands branch to the staging
# environment (ohe-staging.platform-team.all-hands.dev)
#
# Usage:
#   ./create-branch-deployment.sh <branch-name> [--image-tag <tag>]
#
# Examples:
#   ./create-branch-deployment.sh my-feature-branch
#   ./create-branch-deployment.sh fix-login --image-tag sha-abc123
#
# The script:
# 1. Sanitizes the branch name for Kubernetes resources
# 2. Creates a values file at testenv-charts/helm/environments/staging/branch-<name>.yaml
# 3. Outputs helm install commands
#
# Prerequisites:
# - kubectl access to the staging cluster
# - Secrets copied from all-hands-system namespace (use copy-secrets.sh)
# =============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
BASE_DOMAIN="ohe-staging.platform-team.all-hands.dev"
AUTH_HOST="auth.ohe-staging.platform-team.all-hands.dev"
RUNTIME_DOMAIN="runtime.ohe-staging.platform-team.all-hands.dev"
LLM_PROXY_URL="https://llm-proxy.ohe-staging.platform-team.all-hands.dev/"
KEYCLOAK_REALM="allhands"
KEYCLOAK_CLIENT_ID="allhands"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
VALUES_DIR="${REPO_ROOT}/testenv-charts/helm/environments/staging"

# Default values
IMAGE_TAG=""
IMAGE_REPO="ghcr.io/openhands/enterprise-server"

usage() {
    echo "Usage: $0 <branch-name> [options]"
    echo ""
    echo "Arguments:"
    echo "  branch-name    The branch name to deploy (will be sanitized for k8s)"
    echo ""
    echo "Options:"
    echo "  --image-tag    Docker image tag (default: uses latest from main)"
    echo "  --image-repo   Docker image repository (default: ghcr.io/openhands/enterprise-server)"
    echo "  --help         Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0 my-feature-branch"
    echo "  $0 feature/new-ui --image-tag sha-abc123"
    echo "  $0 fix-bug-123 --image-tag pr-456"
    exit 1
}

# Sanitize branch name for Kubernetes (must be DNS-1123 compliant)
sanitize_branch_name() {
    local branch="$1"
    # Convert to lowercase, replace / and _ with -, remove invalid chars, trim to 63 chars
    echo "$branch" | tr '[:upper:]' '[:lower:]' | tr '/' '-' | tr '_' '-' | sed 's/[^a-z0-9-]//g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//' | cut -c1-63
}

info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

# Parse arguments
BRANCH_NAME=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --image-tag)
            IMAGE_TAG="$2"
            shift 2
            ;;
        --image-repo)
            IMAGE_REPO="$2"
            shift 2
            ;;
        --help|-h)
            usage
            ;;
        -*)
            error "Unknown option: $1"
            ;;
        *)
            if [[ -z "$BRANCH_NAME" ]]; then
                BRANCH_NAME="$1"
            else
                error "Too many arguments"
            fi
            shift
            ;;
    esac
done

if [[ -z "$BRANCH_NAME" ]]; then
    error "Branch name is required"
fi

# Sanitize the branch name
SANITIZED_NAME=$(sanitize_branch_name "$BRANCH_NAME")
if [[ -z "$SANITIZED_NAME" ]]; then
    error "Branch name '$BRANCH_NAME' results in empty sanitized name"
fi

info "Branch name: $BRANCH_NAME"
info "Sanitized name: $SANITIZED_NAME"

# Calculate derived values
NAMESPACE="openhands-${SANITIZED_NAME}"
HOST="${SANITIZED_NAME}.${BASE_DOMAIN}"
FULLNAME_OVERRIDE="openhands-${SANITIZED_NAME}"
VALUES_FILE="${VALUES_DIR}/branch-${SANITIZED_NAME}.yaml"

info "Namespace: $NAMESPACE"
info "Host: $HOST"
info "Values file: $VALUES_FILE"

# Check if file already exists
if [[ -f "$VALUES_FILE" ]]; then
    warn "Values file already exists: $VALUES_FILE"
    read -p "Overwrite? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        info "Aborted"
        exit 0
    fi
fi

# Create values directory if needed
mkdir -p "$VALUES_DIR"

# Determine image tag
if [[ -z "$IMAGE_TAG" ]]; then
    warn "No image tag specified, using placeholder. Update 'image.tag' before deploying."
    IMAGE_TAG="REPLACE_WITH_YOUR_IMAGE_TAG"
fi

# Generate the values file
cat > "$VALUES_FILE" << EOF
# =============================================================================
# Branch deployment: ${BRANCH_NAME}
# Generated by create-branch-deployment.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================================
# This file overrides base-values.yaml for the ${SANITIZED_NAME} branch deployment
# Uses shared infrastructure from the 'openhands' namespace (PostgreSQL, Redis, LiteLLM)
#
# Deploy with:
#   helm upgrade --install ${NAMESPACE} ./charts/openhands \\
#     -f testenv-charts/helm/environments/staging/base-values.yaml \\
#     -f testenv-charts/helm/environments/staging/branch-${SANITIZED_NAME}.yaml \\
#     -n ${NAMESPACE} --create-namespace
#
# Prerequisites:
#   1. Create namespace: kubectl create namespace ${NAMESPACE}
#   2. Copy secrets from openhands namespace:
#      for secret in ghcr-login-secret postgres-password redis keycloak-admin openhands-api-key; do
#        kubectl get secret \$secret -n openhands -o yaml | \\
#          sed "s/namespace: openhands/namespace: ${NAMESPACE}/" | \\
#          kubectl apply -f -
#      done
# =============================================================================

# Branch-specific naming
fullnameOverride: ${FULLNAME_OVERRIDE}

# Branch-specific image
# NOTE: For PR deployments, build enterprise-server from your PR branch
# The open-source ghcr.io/openhands/openhands image lacks SaaS backend features
image:
  repository: ${IMAGE_REPO}
  tag: ${IMAGE_TAG}
  pullPolicy: Always

# =============================================================================
# Authentication - Use Shared Keycloak
# =============================================================================
# The staging environment has a shared Keycloak at ${AUTH_HOST}
# Each branch uses the same Keycloak realm but needs its redirect URI registered
keycloak:
  enabled: false
  # CRITICAL: Set authHost to point to shared Keycloak
  # Without this, the chart computes AUTH_URL as auth.${HOST} which doesn't exist
  authHost: ${AUTH_HOST}
  # Register this branch's redirect URI with the shared Keycloak
  redirectUriRegistration:
    enabled: true
    keycloakUrl: "https://${AUTH_HOST}"
    realmName: "${KEYCLOAK_REALM}"
    clientId: "${KEYCLOAK_CLIENT_ID}"
    adminUser: "admin"
    adminPasswordSecret:
      name: "keycloak-admin"
      key: "admin-password"
keycloakConfig:
  enabled: false

# Enable Enterprise SSO button on frontend
enterpriseSSO:
  enabled: true

# =============================================================================
# Environment Configuration
# =============================================================================
env:
  # Runtime Configuration (uses shared runtime-api)
  RUNTIME_URL_PATTERN: https://{runtime_id}.${RUNTIME_DOMAIN}
  
  # LLM Proxy (shared)
  OPENHANDS_PROVIDER_BASE_URL: ${LLM_PROXY_URL}
  
  # Features - Minimal for branch testing (enable as needed)
  ENABLE_BILLING: "false"
  ENABLE_EXPERIMENT_MANAGER: "false"
  ENABLE_MCP_SEARCH_ENGINE: "false"
  ENABLE_PROACTIVE_CONVERSATION_STARTERS: "false"
  ENABLE_SOLVABILITY_ANALYSIS: "false"
  ENABLE_V1_GITHUB_RESOLVER: "false"
  ENABLE_V1_SLACK_RESOLVER: "false"
  
  # UI Flags
  OH_WEB_CLIENT_FEATURE_FLAGS_ENABLE_BILLING: "false"
  OH_WEB_CLIENT_FEATURE_FLAGS_ENABLE_JIRA: "false"
  OH_WEB_CLIENT_FEATURE_FLAGS_HIDE_BILLING_PAGE: "true"
  OH_WEB_CLIENT_FEATURE_FLAGS_HIDE_INTEGRATIONS_PAGE: "false"
  OH_WEB_CLIENT_FEATURE_FLAGS_HIDE_USERS_PAGE: "false"
  
  # Access Control (allow internal emails for testing)
  DUPLICATE_EMAIL_CHECK: "false"
  OH_USER_AUTHORIZER_PREVENT_DUPLICATES: "false"
  EMAIL_PATTERN_BLACKLIST: '%'
  EMAIL_PATTERN_WHITELIST: '%@openhands.dev,%@all-hands.dev'

# =============================================================================
# Disable Integrations (not needed for branch testing)
# =============================================================================
github:
  enabled: false
githubProxy:
  enabled: false
gitlab:
  enabled: false
gitlabWebhookInstallation:
  enabled: false
slack:
  enabled: false
stripe:
  enabled: false
linear:
  enabled: false
jira:
  enabled: false
resend:
  enabled: false
resendSync:
  enabled: false
bitbucket:
  enabled: false
tavily:
  enabled: false

# =============================================================================
# Disable Services (use shared from main deployment)
# =============================================================================
runtime-api:
  enabled: false
automation:
  enabled: false
  events:
    enabled: false
automationEvents:
  enabled: false
automationServiceKey:
  enabled: false
automationWebhookSecret:
  enabled: false
automationService:
  eventForwardingEnabled: false
mcp:
  enabled: false
mcpEvents:
  enabled: false
integrations:
  enabled: false
integrationEvents:
  enabled: false
pluginDirectory:
  enabled: false

# =============================================================================
# Use Shared PostgreSQL
# =============================================================================
postgresql:
  enabled: false
databaseMigrations:
  waitForDatabase: true
  createDatabases: false
  migrate: false  # Migrations run by main deployment
externalDatabase:
  host: openhands-postgresql.openhands.svc.cluster.local
  port: 5432
  username: postgres
  database: openhands
  existingSecret: postgres-password
  secretKey: postgres-password

# =============================================================================
# Use Shared Redis
# =============================================================================
redis:
  enabled: false
redisConnection:
  host: openhands-redis-master.openhands.svc.cluster.local
  port: 6379
  existingSecret: redis
  secretKey: redis-password

# =============================================================================
# Use Shared LiteLLM
# =============================================================================
litellm-helm:
  enabled: false
litellm:
  url: "http://openhands-litellm.openhands.svc.cluster.local:4000"

# =============================================================================
# MinIO - Per-branch instance (needed for file storage)
# =============================================================================
minio:
  enabled: true
  fullnameOverride: ${FULLNAME_OVERRIDE}-minio

# =============================================================================
# Ingress Configuration
# =============================================================================
ingress:
  enabled: true
  className: traefik
  host: ${HOST}
  prefixWithBranch: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: ${HOST}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - ${HOST}
      secretName: ohe-staging-wildcard-tls

# =============================================================================
# Disable DataDog (for branch testing)
# =============================================================================
datadog:
  enabled: false
EOF

success "Created values file: $VALUES_FILE"

# Output deployment instructions
echo ""
echo "============================================================================="
echo "DEPLOYMENT INSTRUCTIONS"
echo "============================================================================="
echo ""
echo "1. Create the namespace and copy secrets:"
echo "   ${GREEN}kubectl create namespace ${NAMESPACE}${NC}"
echo ""
echo "   # Copy required secrets from openhands namespace:"
echo "   ${GREEN}for secret in ghcr-login-secret postgres-password redis keycloak-admin openhands-api-key; do"
echo "     kubectl get secret \$secret -n openhands -o yaml | \\"
echo "       sed \"s/namespace: openhands/namespace: ${NAMESPACE}/\" | \\"
echo "       kubectl apply -f -"
echo "   done${NC}"
echo ""
echo "2. Deploy the branch:"
echo "   ${GREEN}helm upgrade --install ${NAMESPACE} ./charts/openhands \\"
echo "     -f testenv-charts/helm/environments/staging/base-values.yaml \\"
echo "     -f testenv-charts/helm/environments/staging/branch-${SANITIZED_NAME}.yaml \\"
echo "     -n ${NAMESPACE}${NC}"
echo ""
echo "3. Register redirect URI with Keycloak (if redirectUriRegistration doesn't auto-run):"
echo "   ${GREEN}# Manual registration via Keycloak Admin Console:"
echo "   # Navigate to: Realm Settings > Clients > ${KEYCLOAK_CLIENT_ID} > Valid Redirect URIs"
echo "   # Add: https://${HOST}/*${NC}"
echo ""
echo "4. Access your deployment:"
echo "   ${GREEN}https://${HOST}${NC}"
echo ""
echo "5. Check pod status:"
echo "   ${GREEN}kubectl get pods -n ${NAMESPACE}${NC}"
echo ""
echo "============================================================================="

if [[ "$IMAGE_TAG" == "REPLACE_WITH_YOUR_IMAGE_TAG" ]]; then
    warn "Remember to update 'image.tag' in $VALUES_FILE before deploying!"
fi
