{{- if .Values.replicated.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-preflight
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    troubleshoot.sh/kind: preflight
stringData:
  preflight.yaml: |- {{- include "runtime.troubleshoot.preflights" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-support-bundle
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    troubleshoot.sh/kind: support-bundle
stringData:
  support-bundle-spec: |- {{- include "runtime.troubleshoot.supportBundle" . | nindent 4 }}
{{- end }}
