{{- if .Values.events.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: automation-events
  labels:
    app: automation-events
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: automation-events
{{- end }}
