apiVersion: v1
kind: Service
metadata:
  name: automation
  labels:
    app: automation
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: automation
