{{- if .Values.automation.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: automation-kv-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  kv-secret: {{ .Values.config.automation_kv_secret | b64enc | quote }}
{{- end }}
