{{- if .Values.automation.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: automation-git-sync-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  git-sync-secret: {{ .Values.config.automation_git_sync_secret | b64enc | quote }}
{{- end }}
