{{- if .Values.automation.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: automation-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  db-password: {{ .Values.config.automations_db_password | default .Values.config.postgres_password | b64enc | quote }}
{{- end }}
