{{- if or .Values.config.bitbucket_data_center_domain .Values.config.bitbucket_data_center_client_id .Values.config.bitbucket_data_center_client_secret .Values.config.bitbucket_data_center_bot_token }}
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-data-center-app
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.config.bitbucket_data_center_domain }}
  host: {{ .Values.config.bitbucket_data_center_domain | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.bitbucket_data_center_client_id }}
  client-id: {{ .Values.config.bitbucket_data_center_client_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.bitbucket_data_center_client_secret }}
  client-secret: {{ .Values.config.bitbucket_data_center_client_secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.bitbucket_data_center_bot_token }}
  bot-token: {{ .Values.config.bitbucket_data_center_bot_token | b64enc | quote }}
  {{- end }}
{{- end }}
