{{- if or .Values.config.jira_data_center_base_url .Values.config.jira_data_center_client_id .Values.config.jira_data_center_client_secret .Values.config.jira_data_center_service_account_email .Values.config.jira_data_center_service_account_pat }}
apiVersion: v1
kind: Secret
metadata:
  name: jira-dc-app
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.config.jira_data_center_base_url }}
  base-url: {{ .Values.config.jira_data_center_base_url | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.jira_data_center_client_id }}
  client-id: {{ .Values.config.jira_data_center_client_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.jira_data_center_client_secret }}
  client-secret: {{ .Values.config.jira_data_center_client_secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.jira_data_center_service_account_email }}
  service-account-email: {{ .Values.config.jira_data_center_service_account_email | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.jira_data_center_service_account_pat }}
  service-account-pat: {{ .Values.config.jira_data_center_service_account_pat | b64enc | quote }}
  {{- end }}
{{- end }}
