apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  admin-password: {{ .Values.config.keycloak_admin_password | b64enc | quote }}
  admin-ui-password: {{ .Values.config.keycloak_admin_ui_password | default "" | b64enc | quote }}
