{{- if or .Values.config.smtp_username .Values.config.smtp_password }}
apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.config.smtp_username }}
  smtp-username: {{ .Values.config.smtp_username | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.smtp_password }}
  smtp-password: {{ .Values.config.smtp_password | b64enc | quote }}
  {{- end }}
{{- end }}
