apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: openhands
spec:
  title: OpenHands
  icon: https://raw.githubusercontent.com/All-Hands-AI/OpenHands/main/frontend/public/apple-touch-icon.png
  releaseNotes: |
    ## OpenHands v0.47.0

    OpenHands is an AI-driven autonomous software engineer that can help you build, debug, and deploy applications.

  additionalNamespaces:
    - openhands
    - cert-manager

  statusInformers:
    # openhands
    - openhands/deployment/openhands
    - openhands/service/openhands-service
    - openhands/ingress/openhands-root-ingress
    - openhands/deployment/openhands-integrations
    - openhands/service/openhands-integrations-service
    - openhands/ingress/openhands-integrations-ingress
    - openhands/deployment/openhands-mcp
    - openhands/service/openhands-mcp-service
    - openhands/ingress/openhands-mcp-ingress
    - '{{repl if ConfigOptionEquals "automations_enabled" "1" }}openhands/deployment/automation{{repl end}}'
    - '{{repl if ConfigOptionEquals "automations_enabled" "1" }}openhands/service/automation{{repl end}}'
    - '{{repl if ConfigOptionEquals "automations_enabled" "1" }}openhands/ingress/openhands-automation-ingress{{repl end}}'

    # keycloak
    - openhands/statefulset/keycloak
    - openhands/service/keycloak

    # laminar (for analytics)
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/deployment/laminar-app-server{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/deployment/laminar-app-server-consumer{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/deployment/laminar-frontend{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/deployment/laminar-query-engine{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/deployment/laminar-quickwit-control-plane{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/deployment/laminar-quickwit-janitor{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/deployment/laminar-quickwit-metastore{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/deployment/laminar-redis{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-app-server-consumer-service{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-app-server-service{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-clickhouse-headless{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-clickhouse-service{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-frontend-service{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-postgres-headless{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-postgres-service{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-query-engine-service{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-quickwit-control-plane{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-quickwit-headless{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-quickwit-indexer{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-quickwit-janitor{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-quickwit-metastore{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-quickwit-searcher{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-rabbitmq-headless{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-rabbitmq-service{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/service/laminar-redis-service{{repl end}}'
    - '{{repl if ConfigOptionEquals "analytics_enabled" "1" }}openhands/ingress/laminar-frontend-ingress{{repl end}}'

    # postgres
    - '{{repl if ConfigOptionEquals "postgres_type" "embedded_postgres"}}openhands/statefulset/openhands-postgresql{{repl end}}'
    - '{{repl if ConfigOptionEquals "postgres_type" "embedded_postgres"}}openhands/service/openhands-postgresql{{repl end}}'

    # redis
    - openhands/statefulset/openhands-redis-master
    - openhands/service/openhands-redis-master

    # lite-llm
    - openhands/deployment/openhands-litellm
    - openhands/service/openhands-litellm

    # minio
    - openhands/deployment/openhands-minio
    - openhands/service/openhands-minio

    # runtime-api chart
    - openhands/deployment/openhands-runtime-api
    - openhands/service/openhands-runtime-api
    - openhands/ingress/openhands-runtime-api-ingress
  ports:
    - serviceName: openhands
      servicePort: 3000
      localPort: 3000
      applicationUrl: "http://openhands"
