name: Lint Workflows

# Linter for github actions specifically. Surfaces rules YAML wouldn't notice
# like attempting arithmetic in action files
on:
  pull_request:
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run actionlint
        env:
          ACTIONLINT_VERSION: '1.7.12'
        run: |
          bash <(curl -sSf "https://raw.githubusercontent.com/rhysd/actionlint/v${ACTIONLINT_VERSION}/scripts/download-actionlint.bash") "$ACTIONLINT_VERSION"
          ./actionlint -color
